import {
  Activity,
  Baby,
  Banknote,
  Beef,
  Bike,
  BookOpen,
  Boxes,
  Briefcase,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  Camera,
  Car,
  CarFront,
  Cat,
  CircleDollarSign,
  Clapperboard,
  Coffee,
  Coins,
  Cookie,
  CreditCard,
  Dog,
  Droplets,
  Dumbbell,
  Flower2,
  Fuel,
  Gamepad2,
  Gift,
  GlassWater,
  GraduationCap,
  Hamburger,
  Hammer,
  HandCoins,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  House,
  IceCream,
  Key,
  Lamp,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  Lock,
  MapPin,
  Megaphone,
  Monitor,
  Music,
  Package,
  Paintbrush,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PlaneTakeoff,
  Receipt,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Soup,
  Sparkles,
  Stethoscope,
  Store,
  Tag,
  TrainFront,
  Truck,
  Tv,
  Umbrella,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export interface IconEntry {
  name: string;
  Icon: LucideIcon;
}

export const ICONS: IconEntry[] = [
  { name: "Home", Icon: Home },
  { name: "House", Icon: House },
  { name: "Building", Icon: Building },
  { name: "Building2", Icon: Building2 },
  { name: "Briefcase", Icon: Briefcase },
  { name: "Wallet", Icon: Wallet },
  { name: "Banknote", Icon: Banknote },
  { name: "Landmark", Icon: Landmark },
  { name: "CreditCard", Icon: CreditCard },
  { name: "CircleDollarSign", Icon: CircleDollarSign },
  { name: "HandCoins", Icon: HandCoins },
  { name: "Coins", Icon: Coins },
  { name: "Calculator", Icon: Calculator },
  { name: "PiggyBank", Icon: PiggyBank },
  { name: "ShoppingCart", Icon: ShoppingCart },
  { name: "ShoppingBasket", Icon: ShoppingBasket },
  { name: "ShoppingBag", Icon: ShoppingBag },
  { name: "Store", Icon: Store },
  { name: "Utensils", Icon: Utensils },
  { name: "UtensilsCrossed", Icon: UtensilsCrossed },
  { name: "Pizza", Icon: Pizza },
  { name: "Hamburger", Icon: Hamburger },
  { name: "Soup", Icon: Soup },
  { name: "Cake", Icon: Cake },
  { name: "Cookie", Icon: Cookie },
  { name: "Coffee", Icon: Coffee },
  { name: "GlassWater", Icon: GlassWater },
  { name: "Wine", Icon: Wine },
  { name: "Beef", Icon: Beef },
  { name: "Fuel", Icon: Fuel },
  { name: "Car", Icon: Car },
  { name: "CarFront", Icon: CarFront },
  { name: "Bus", Icon: Bus },
  { name: "TrainFront", Icon: TrainFront },
  { name: "Bike", Icon: Bike },
  { name: "Truck", Icon: Truck },
  { name: "Plane", Icon: Plane },
  { name: "PlaneTakeoff", Icon: PlaneTakeoff },
  { name: "MapPin", Icon: MapPin },
  { name: "Gamepad2", Icon: Gamepad2 },
  { name: "Clapperboard", Icon: Clapperboard },
  { name: "Music", Icon: Music },
  { name: "Camera", Icon: Camera },
  { name: "Tv", Icon: Tv },
  { name: "Headphones", Icon: Headphones },
  { name: "Dumbbell", Icon: Dumbbell },
  { name: "Smartphone", Icon: Smartphone },
  { name: "Phone", Icon: Phone },
  { name: "Monitor", Icon: Monitor },
  { name: "Laptop", Icon: Laptop },
  { name: "Wifi", Icon: Wifi },
  { name: "Zap", Icon: Zap },
  { name: "Lamp", Icon: Lamp },
  { name: "Lightbulb", Icon: Lightbulb },
  { name: "Droplets", Icon: Droplets },
  { name: "Receipt", Icon: Receipt },
  { name: "Megaphone", Icon: Megaphone },
  { name: "Boxes", Icon: Boxes },
  { name: "Package", Icon: Package },
  { name: "Pill", Icon: Pill },
  { name: "Stethoscope", Icon: Stethoscope },
  { name: "Heart", Icon: Heart },
  { name: "HeartPulse", Icon: HeartPulse },
  { name: "Activity", Icon: Activity },
  { name: "GraduationCap", Icon: GraduationCap },
  { name: "BookOpen", Icon: BookOpen },
  { name: "PawPrint", Icon: PawPrint },
  { name: "Dog", Icon: Dog },
  { name: "Cat", Icon: Cat },
  { name: "Baby", Icon: Baby },
  { name: "Shirt", Icon: Shirt },
  { name: "Scissors", Icon: Scissors },
  { name: "Flower2", Icon: Flower2 },
  { name: "Leaf", Icon: Leaf },
  { name: "Wrench", Icon: Wrench },
  { name: "Hammer", Icon: Hammer },
  { name: "Paintbrush", Icon: Paintbrush },
  { name: "Gift", Icon: Gift },
  { name: "Sparkles", Icon: Sparkles },
  { name: "Key", Icon: Key },
  { name: "Lock", Icon: Lock },
  { name: "Umbrella", Icon: Umbrella },
  { name: "Tag", Icon: Tag },
];

const ICONS_BY_NAME: Record<string, LucideIcon> = Object.fromEntries(
  ICONS.map((i) => [i.name, i.Icon]),
);

/** Retorna o componente do ícone, com fallback para Tag. */
export function getCategoryIcon(name?: string | null): LucideIcon {
  if (name && ICONS_BY_NAME[name]) return ICONS_BY_NAME[name] ?? Tag;
  return Tag;
}

const normalize = (s: string) =>
  s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim();

const KEYWORD_ICONS: Array<[string[], string]> = [
  [["casa", "moradia", "residencia", "imovel", "lar"], "Home"],
  [["aluguel", "aluguer", "condominio"], "Building2"],
  [["empresa", "escritorio", "negocio", "firma", "corporativo", "pj"], "Building"],
  [["trabalho", "emprego", "profissao", "carreira", "clt"], "Briefcase"],
  [["salario", "ordenado", "holerite", "recebimento", "pagamento"], "Wallet"],
  [["banco", "juros", "investimento", "financeiro"], "Landmark"],
  [["cartao", "fatura", "credito", "debito"], "CreditCard"],
  [
    [
      "mercado",
      "supermercado",
      "mercearia",
      "feira",
      "acougue",
      "hortifruti",
      "padaria",
      "quitanda",
    ],
    "ShoppingCart",
  ],
  [["compras", "loja", "varejo", "shopping", "boutique"], "ShoppingBag"],
  [["alimentacao", "comida", "cozinha", "lanche", "almoco", "jantar", "cafe"], "Utensils"],
  [
    ["restaurante", "lanchonete", "fastfood", "hamburgueria", "pizzaria", "churrascaria"],
    "UtensilsCrossed",
  ],
  [["combustivel", "gasolina", "etanol", "diesel", "posto"], "Fuel"],
  [["carro", "automovel", "veiculo", "uber", "taxi", "estacionamento"], "Car"],
  [["viagem", "passagem", "aereo", "voo", "turismo", "ferias", "hotel"], "Plane"],
  [
    [
      "lazer",
      "jogo",
      "games",
      "videogame",
      "diversao",
      "entretenimento",
      "cinema",
      "show",
      "festa",
    ],
    "Gamepad2",
  ],
  [["celular", "telefone", "smartphone", "aparelho"], "Smartphone"],
  [["internet", "wifi", "telefonia", "fibra", "banda larga", "assinatura"], "Wifi"],
  [["energia", "luz", "eletricidade", "eletrica"], "Zap"],
  [["agua", "saneamento", "encanamento"], "Droplets"],
  [["impostos", "imposto", "taxa", "tributo", "guia", "ipva", "darf"], "Receipt"],
  [
    [
      "publicacao",
      "propaganda",
      "anuncio",
      "marketing",
      "publicidade",
      "divulgacao",
      "midia",
      "ads",
    ],
    "Megaphone",
  ],
  [["insumos", "estoque", "materia prima", "materiais", "suprimentos", "fornecedor"], "Boxes"],
  [["farmacia", "remedio", "medicamento", "farmaceutico"], "Pill"],
  [
    ["saude", "medico", "consulta", "hospital", "clinica", "dentista", "plano de saude", "exame"],
    "HeartPulse",
  ],
  [
    [
      "educacao",
      "escola",
      "curso",
      "faculdade",
      "universidade",
      "colegio",
      "mensalidade",
      "ensino",
      "matricula",
    ],
    "GraduationCap",
  ],
  [["pet", "pets", "animal", "cachorro", "gato", "veterinario", "racao"], "PawPrint"],
  [["roupa", "vestuario", "calcado", "moda"], "Shirt"],
  [["beleza", "cabelo", "barbearia", "salao"], "Scissors"],
  [["crianca", "filho", "bebe", "infantil"], "Baby"],
  [["doacao", "presente", "presentes"], "Gift"],
];

/** Sugere um ícone a partir do nome da categoria. */
export function suggestIcon(name: string): string {
  const n = normalize(name);
  if (!n) return "Tag";
  for (const [keywords, icon] of KEYWORD_ICONS) {
    if (keywords.some((k) => n.includes(k))) return icon;
  }
  return "Tag";
}
